const genList = [
    {
        id: 1,
        question_one: "1. How to get to Siargao?",
        answer_one: "To reach Siargao, book a domestic flight to Sayak Airport from Cebu. If you prefer a scenic route, you can optionally take a ferry from Surigao City. Once you arrive, make arrangements for local transportation to your accommodation.",
        question_two: "2. When is the best time to go to Siargao?",
        answer_two: "It depends on what you’re looking for! September is by far the busiest month. The national & international surfing competitions and the town fiesta are all in September. If you’re looking for epic surf, the waves are best from September to November. If you’re looking for uncrowded surf, come from December to March. It’s uncrowded because it’s raining. A lot. If you want to learn how to surf, come anytime. If you have no idea why everyone keeps talking about surfing, then April to October are perfect for beach all day and party all night.",
        question_three: "3. What are the must-do activities in Siargao?",
        answer_three: "In Siargao, you must surf at Cloud 9, go island hopping to Naked Island, Guyam Island, and Daku Island, explore Sugba Lagoon, visit the unique Magpupungko Rock Pools, and enjoy the vibrant nightlife in General Luna.",
        question_four: "4. Where to stay in Siargao?",
        answer_four: "Popular areas to stay in Siargao include General Luna, Cloud 9, and nearby villages like Pacifico and Dapa. These areas offer a range of accommodations, from hostels to luxury resorts, to suit different budgets and preferences.",
        question_five: "5. How much does it cost to travel to Siargao?",
        answer_five: "A budget traveler in Siargao might spend around 1,500 to 2,500 Philippine Pesos per day, while a mid-range traveler could budget for 2,500 to 5,000 Philippine Pesos per day. For luxury travelers, the daily expenses could exceed 5,000 Philippine Pesos. Domestic flights typically range from 7,500 to 16,000 Philippine Pesos round trip, depending on your departure location and booking timing.",
        question_six: "6. What is the currency in Siargao?",
        answer_six: "The currency used in Siargao, Philippines, is the Philippine Peso (PHP).",
        question_seven: "7. Is it safe to travel to Siargao?",
        answer_seven: "Siargao is generally safe for travelers. However, exercise common travel precautions, such as securing belongings and being mindful of the weather and sea conditions. Stay updated on any local advisories and health recommendations.",
        question_eight: "8. What are the visa requirements for Siargao?",
        answer_eight: "Most tourists can enter the Philippines without a visa for 30 days. If needed, you can extend your stay. Check the latest visa rules and ensure your passport is valid for at least six months beyond your intended departure date.",
        question_nine: "9. How can I get around in Siargao?",
        answer_nine: "You can get around Siargao by using tricycles, habal-habal (motorcycle taxis), rented scooters or bicycles, and vans or private vehicles.",  
        question_ten: "10. What is the weather like in Siargao?",
        answer_ten: "Siargaoo has a tropical climate with a wet season from November to February and a dry season from March to October. The best time to visit is during the dry season for sunny weather.",
        language: "english"
    },
    {
        id: 2,
        question_one: "1. ¿Cómo llegar a Siargao?",
        answer_one: "Para llegar a Siargao, reserva un vuelo nacional al Aeropuerto de Sayak desde Cebú. Si prefieres una ruta escénica, también puedes tomar un ferry desde la ciudad de Surigao. Una vez que llegues, organiza el transporte local hacia tu alojamiento.",
        question_two: "2. ¿Cuál es la mejor época para ir a Siargao?",
        answer_two: "¡Depende de lo que estés buscando! Septiembre es de lejos el mes más concurrido, con competiciones de surf nacionales e internacionales y la fiesta del pueblo, todo en septiembre. Si buscas olas épicas, lo mejor es de septiembre a noviembre. Si buscas surf sin multitudes, ven de diciembre a marzo. Está tranquilo porque está lloviendo. Mucho. Si quieres aprender a hacer surf, ven en cualquier momento. Si no tienes idea de por qué todos hablan de surf, entonces de abril a octubre es perfecto para la playa durante el día y la fiesta durante la noche. ",
        question_three: "3. ¿Cuáles son las actividades imprescindibles en Siargao?",
        answer_three: "En Siargao, debes surfear en Cloud 9, hacer un recorrido por las islas Naked, Guyam y Daku, explorar la Laguna Sugba, visitar las singulares Piscinas de Roca de Magpupungko y disfrutar de la animada vida nocturna en General Luna.",
        question_four: "4. ¿Dónde hospedarse en Siargao?",
        answer_four: "Las áreas populares para hospedarse en Siargao incluyen General Luna, Cloud 9 y pueblos cercanos como Pacifico y Dapa. Estas áreas ofrecen una variedad de alojamientos, desde hostales hasta resorts de lujo, para adaptarse a diferentes presupuestos y preferencias.",
        question_five: "5. ¿Cuánto cuesta viajar a Siargao?",
        answer_five: "Un viajero con presupuesto en Siargao podría gastar alrededor de 1,500 a 2,500 pesos filipinos por día, mientras que un viajero de rango medio podría presupuestar de 2,500 a 5,000 pesos filipinos por día. Para viajeros de lujo, los gastos diarios podrían superar los 5,000 pesos filipinos. Los vuelos nacionales suelen oscilar entre 7,500 y 16,000 pesos filipinos ida y vuelta, dependiendo de tu ubicación de salida y el momento de la reserva.",
        question_six: "6. ¿Cuál es la moneda en Siargao?",
        answer_six: "La moneda utilizada en Siargao, Filipinas, es el Peso Filipino (PHP). ",
        question_seven: "7. ¿Es seguro viajar a Siargao? ",
        answer_seven: "Siargao es generalmente seguro para los viajeros. Sin embargo, sigue precauciones comunes de viaje, como asegurar pertenencias y tener en cuenta las condiciones meteorológicas y del mar. Mantente actualizado sobre cualquier aviso local y recomendaciones de salud. ",
        question_eight: "8. ¿Cuáles son los requisitos de visa para Siargao?",
        answer_eight: "La mayoría de los turistas pueden ingresar a Filipinas sin visa durante 30 días. Si es necesario, puedes extender tu estancia. Verifica las últimas reglas de visa y asegúrate de que tu pasaporte tenga validez por al menos seis meses más allá de tu fecha de salida prevista.",
        question_nine: "9. ¿Cómo moverse en Siargao? ",
        answer_nine: "Puedes desplazarte por Siargao utilizando triciclos, habal-habal (taxis en motocicleta), scooters o bicicletas alquiladas, y vans o vehículos privados.",  
        question_ten: "10. ¿Cómo es el clima en Siargao?",
        answer_ten: "Siargao tiene un clima tropical con una temporada de lluvias de noviembre a febrero y una temporada seca de marzo a octubre. La mejor época para visitar es durante la temporada seca para tener un clima soleado.",
        language: "spanish"
    },
    {
        id: 3,
        question_one: "1. Wie kommt man nach Siargao?",
        answer_one: "Um nach Siargao zu gelangen, buchen Sie einen Inlandsflug zum Flughafen Sayak von Cebu aus. Wenn Sie eine malerische Route bevorzugen, können Sie optional eine Fähre von Surigao City nehmen. Sobald Sie ankommen, arrangieren Sie den lokalen Transport zu Ihrer Unterkunft.",
        question_two: "2. Wann ist die beste Zeit, um nach Siargao zu gehen?",
        answer_two: "Es kommt darauf an, was Sie suchen! September ist bei weitem der geschäftigste Monat. Die nationalen und internationalen Surfwettbewerbe sowie das Stadtfest finden alle im September statt. Wenn Sie epische Wellen suchen, sind die besten Wellen von September bis November. Wenn Sie nach unberührten Wellen suchen, kommen Sie von Dezember bis März. Es ist unberührt, weil es regnet. Viel. Wenn Sie lernen möchten, wie man surft, kommen Sie jederzeit. Wenn Sie keine Ahnung haben, warum alle ständig über Surfen reden, sind April bis Oktober perfekt für den ganztägigen Strand und die ganze Nacht Party.",
        question_three: "3. Was sind die Must-Do-Aktivitäten in Siargao?",
        answer_three: "In Siargao müssen Sie am Cloud 9 surfen, Inselhüpfen zu Naked Island, Guyam Island und Daku Island machen, Sugba Lagoon erkunden, die einzigartigen Magpupungko Rock Pools besuchen und das lebhafte Nachtleben in General Luna genießen.",
        question_four: "4. Wo übernachtet man in Siargao?",
        answer_four: "Beliebte Gegenden, um in Siargao zu übernachten, sind General Luna, Cloud 9 und nahegelegene Dörfer wie Pacifico und Dapa. Diese Gebiete bieten eine Vielzahl von Unterkünften, von Hostels bis hin zu Luxusresorts, die verschiedenen Budgets und Vorlieben entsprechen.",
        question_five: "5. Wie viel kostet eine Reise nach Siargao? ",
        answer_five: "Ein Budgetreisender in Siargao könnte etwa 1.500 bis 2.500 Philippinische Pesos pro Tag ausgeben, während ein Reisender im mittleren Preissegment mit 2.500 bis 5.000 Philippinische Pesos pro Tag rechnen könnte. Für Luxusreisende könnten die täglichen Ausgaben 5.000 Philippinische Pesos überschreiten. Inlandsflüge kosten in der Regel zwischen 7.500 und 16.000 Philippinische Pesos für Hin- und Rückflug, abhängig von Ihrem Abflugort und der Buchungszeit.",
        question_six: "6. Was ist die Währung in Siargao?",
        answer_six: "Die in Siargao, Philippinen, verwendete Währung ist der Philippinische Peso (PHP).",
        question_seven: "7. Ist es sicher, nach Siargao zu reisen?",
        answer_seven: "Siargao ist für Reisende im Allgemeinen sicher. Üben Sie jedoch gängige Reisevorsichtsmaßnahmen aus, wie das Sichern von Gegenständen und das Beachten der Wetter- und Meerbedingungen. Halten Sie sich über lokale Empfehlungen und Gesundheitsempfehlungen auf dem Laufenden.",
        question_eight: "8. Was sind die Visabestimmungen für Siargao?",
        answer_eight: "Die meisten Touristen können ohne Visum 30 Tage lang in die Philippinen einreisen. Bei Bedarf können Sie Ihren Aufenthalt verlängern. Überprüfen Sie die aktuellen Visaregelungen und stellen Sie sicher, dass Ihr Reisepass mindestens sechs Monate über Ihr beabsichtigtes Abreisedatum hinaus gültig ist.",
        question_nine: "9. Wie kann ich mich in Siargao fortbewegen?",
        answer_nine: "Sie können Siargao mit Tricycles, Habal-Habal (Motorradtaxis), gemieteten Rollern oder Fahrrädern und Vans oder privaten Fahrzeugen erkunden. ",  
        question_ten: "10. Wie ist das Wetter in Siargao?",
        answer_ten: "Siargao hat ein tropisches Klima mit einer Regenzeit von November bis Februar und einer Trockenzeit von März bis Oktober. Die beste Reisezeit ist während der Trockenzeit für sonniges Wetter.  ",
        language: "german"
    },
    {
        id: 4,
        question_one: "1. Comment se rendre à Siargao?",
        answer_one: "Pour se rendre à Siargao, réservez un vol intérieur vers l'aéroport de Sayak depuis Cebu. Si vous préférez un itinéraire pittoresque, vous pouvez éventuellement prendre un ferry depuis la ville de Surigao. Une fois arrivé, organisez votre transport local jusqu'à votre hébergement.",
        question_two: "2. Quand est le meilleur moment pour aller à Siargao?",
        answer_two: "Cela dépend de ce que vous recherchez ! Septembre est de loin le mois le plus animé. Les compétitions de surf nationales et internationales ainsi que la fête de la ville ont lieu en septembre. Si vous recherchez des vagues épiques, les meilleures périodes sont de septembre à novembre. Si vous cherchez à surfer sans foule, venez de décembre à mars. Il y a peu de monde car il pleut. Beaucoup. Si vous voulez apprendre à surfer, venez à tout moment. Si vous n'avez aucune idée de pourquoi tout le monde parle de surf, alors d'avril à octobre est parfait pour la plage toute la journée et faire la fête toute la nuit.",
        question_three: "3. Quelles sont les activités incontournables à Siargao?",
        answer_three: "À Siargao, vous devez surfer à Cloud 9, faire du saut d'île en île à Naked Island, Guyam Island et Daku Island, explorer la lagune de Sugba, visiter les piscines rocheuses uniques de Magpupungko et profiter de la vie nocturne animée à General Luna.",
        question_four: "4. Où séjourner à Siargao?",
        answer_four: "Les zones populaires pour séjourner à Siargao incluent General Luna, Cloud 9 et les villages voisins comme Pacifico et Dapa. Ces zones offrent une gamme d'hébergements, des auberges aux complexes de luxe, pour convenir à différents budgets et préférences.",
        question_five: "5. Combien coûte un voyage à Siargao?",
        answer_five: "Un voyageur avec un budget limité à Siargao pourrait dépenser environ 1 500 à 2 500 pesos philippins par jour, tandis qu'un voyageur de milieu de gamme pourrait prévoir un budget de 2 500 à 5 000 pesos philippins par jour. Pour les voyageurs de luxe, les dépenses quotidiennes pourraient dépasser 5 000 pesos philippins. Les vols intérieurs coûtent généralement entre 7 500 et 16 000 pesos philippins aller-retour, selon votre lieu de départ et le moment de la réservation.",
        question_six: "6. Quelle est la monnaie utilisée à Siargao? ",
        answer_six: "La monnaie utilisée à Siargao, aux Philippines, est le peso philippin (PHP).",
        question_seven: "7. Est-il sûr de voyager à Siargao?",
        answer_seven: "Siargao est généralement sûr pour les voyageurs. Cependant, prenez des précautions de voyage habituelles, telles que sécuriser vos effets personnels et être attentif aux conditions météorologiques et maritimes. Restez informé des éventuels avis locaux et des recommandations en matière de santé. ",
        question_eight: "8. Quels sont les documents nécessaires pour Siargao?",
        answer_eight: "La plupart des touristes peuvent entrer aux Philippines sans visa pendant 30 jours. Si nécessaire, vous pouvez prolonger votre séjour. Vérifiez les dernières règles en matière de visa et assurez-vous que votre passeport est valide pendant au moins six mois après votre date de départ prévue.",
        question_nine: "9. Comment se déplacer à Siargao?",
        answer_nine: "Vous pouvez vous déplacer à Siargao en utilisant des tricycles, des habal-habal (taxis-motos), des scooters ou des vélos loués, ainsi que des vans ou des véhicules privés. ",  
        question_ten: "10. Quel est le climat à Siargao?",
        answer_ten: "Siargao a un climat tropical avec une saison des pluies de novembre à février et une saison sèche de mars à octobre. Le meilleur moment pour visiter est pendant la saison sèche pour avoir un temps ensoleillé.",
        language: "french"
    },
    {
        id: 5,
        question_one: "1. איך להגיע לסיארג'או?",
        answer_one: "כדי להגיע לסיארג'או, הזמן טיסה פנימית לנמל התעופה שייק מצווי. אם אתה מעדיף מסלול נופש, תוכל לקחת גם סירה מעיר סוריגאו. כאשר אתה מגיע, הסדר תחבורה מקומית לאירוח שלך.",
        question_two: "2. מתי הזמן הכי טוב לבקר בסיארגאו?",
        answer_two: "זה תלוי במה שאתה מחפש! ספטמבר הוא לכל הדעות הכי עמוס. תחרויות הגלישה הלאומיות והבינלאומיות ופסטיבל העיר כולם בספטמבר. אם אתה מחפש גלישה אפייתית, הגלים הם הכי טובים מספטמבר עד נובמבר. אם אתה מחפש גלישה לא מפוצצת, כדאי לבוא מדצמבר עד מרץ. זה לא מפוצץ כי זה גשום. הרבה. אם ברצונך ללמוד לגלוש, אתה יכול לבוא בכל עת. אם אין לך מושג למה כולם ממשיכים לדבר על גלישה, אז אפריל עד אוקטובר הם מושלמים לחוף כל היום ולמסיבה כל הלילה.",
        question_three: "3. מהן הפעילויות החובה בסיארגאו?",
        answer_three: "בסיארגאו, עליך לגלוש בענן 9, לעבור בסיורי איים לאי העירום, גיאם עירום, ודאקו, לחקור את הלגונה של סוגבה, לבקר במגפונקו וליהנות מחיי הלילה הדונמיים בג'נרל לונה.",
        question_four: "4. איפה להישאר בסיארגאו?",
        answer_four: "אזורים פופולריים לשהות בסיארגאו כוללים את ג'נרל לונה, ענן 9, וכפרים קרובים כמו פציפיקו ודאפה. אלה האזורים מציעים מגוון של אירוחים, מהמסלולים למלונות יוקרה, כדי להתאים לתקציבים והעדפות שונות.",
        question_five: "5. כמה עולה הנסיעה לסיארגאו?",
        answer_five: "נוסע בתקציב בסיארגאו עשוי להוציא כ-1,500 עד 2,500 פיסות פיל",
        question_six: "6. מהו המטבע בסיארג'או?",
        answer_six: " המטבע המשמש בסיארג'או, בפיליפינים, הוא הפסו הפיליפיני (PHP).",
        question_seven: "7. האם בטוח לנסוע לסיארג'או?",
        answer_seven: " סיארג'או בכללי בטוחה למטיילים. אף על פי שזה כך, עליך להפעיל את הזהירות הרגילה של מטייל, כמו לאבטח את המ",
        question_eight: "8. מהם דרישות הויזה לסיארג'או?",
        answer_eight: "רוב התיירים יכולים להיכנס לפיליפינים ללא ויזה למשך 30 ימים. אם נדרש, תוכל להאריך את השהייה שלך. בדוק את החוקים האחרונים בנוגע לוויזה ווודא שדרכוך תקפה לפחות ששה חודשים מעבר לתאריך היציאה הנדקדק.",
        question_nine: "9. איך להסתגל בסיארג'או?",
        answer_nine: " אתה יכול להסתגל בסיארג'או על ידי שימוש בטריקילוס, הבל-הבל (מונוסיקל טקסי), קטנועים או אופנועים מושכרים, וואנס או כלי רכב פרטיים.",  
        question_ten: "10. איך המזג האוויר בסיארג'או?",
        answer_ten: " בסיארג'או יש לו מזג אוויר טרופי עם עונת גשם מנובמבר עד לפברואר ועונת יבשה ממרץ עד אוקטובר. הזמן הטוב ביותר לבקר הוא במהלך עונת הייבשה למזג האוויר השמשי.",
        language: "hebrew"
    },
    {
        id: 6,
        question_one: "1. Hoe kom je op Siargao?",
        answer_one: "Om naar Siargao te gaan, boek je een binnenlandse vlucht naar de luchthaven van Sayak vanuit Cebu. Als je liever een schilderachtige route neemt, kun je optioneel een veerboot nemen vanuit Surigao City. Eenmaal aangekomen, regel je lokaal vervoer naar je accommodatie.",
        question_two: "2. Wanneer is de beste tijd om naar Siargao te gaan?",
        answer_two: "Dat hangt af van waar je naar op zoek bent! September is veruit de drukste maand. De nationale en internationale surfwedstrijden en het stadsfeest zijn allemaal in september. Als je op zoek bent naar epische golven, zijn de golven het beste van september tot november. Als je op zoek bent naar onbezette surfplekken, kom dan van december tot maart. Het is rustig omdat het regent. Veel. Als je wilt leren surfen, kom dan op elk moment. Als je geen idee hebt waarom iedereen het steeds over surfen heeft, dan zijn april tot oktober perfect om de hele dag op het strand door te brengen en de hele nacht te feesten.",
        question_three: "3. Wat zijn de must-do activiteiten op Siargao?",
        answer_three: "Op Siargao moet je surfen bij Cloud 9, eilandhoppen naar Naked Island, Guyam Island en Daku Island, Sugba Lagoon verkennen, de unieke Magpupungko Rock Pools bezoeken en genieten van het levendige nachtleven in General Luna.",
        question_four: "4. Waar te verblijven op Siargao?",
        answer_four: "Populaire gebieden om te verblijven op Siargao zijn General Luna, Cloud 9 en nabijgelegen dorpen zoals Pacifico en Dapa. Deze gebieden bieden een scala aan accommodaties, van hostels tot luxe resorts, om verschillende budgetten en voorkeuren tegemoet te komen.",
        question_five: "5. Hoeveel kost het om naar Siargao te reizen?",
        answer_five: "Een budgetreiziger in Siargao kan ongeveer 1.500 tot 2.500 Filipijnse peso per dag uitgeven, terwijl een reiziger met een gemiddeld budget zou kunnen rekenen op 2.500 tot 5.000 Filipijnse peso per dag. Voor luxe reizigers kunnen de dagelijkse kosten meer dan 5.000 Filipijnse peso bedragen. Binnenlandse vluchten variëren meestal van 7.500 tot 16.000 Filipijnse peso voor een retourtje, afhankelijk van je vertreklocatie en de timing van de boeking.",
        question_six: "6. Wat is de valuta op Siargao?",
        answer_six: "De valuta die wordt gebruikt op Siargao, Filipijnen, is de Filipijnse peso (PHP).",
        question_seven: "7. Is het veilig om naar Siargao te reizen?",
        answer_seven: "Siargao is over het algemeen veilig voor reizigers. Oefen echter gebruikelijke reisvoorzorgsmaatregelen uit, zoals het veiligstellen van bezittingen en het opletten van het weer en de zeecondities. Blijf op de hoogte van eventuele lokale waarschuwingen en gezondheidsaanbevelingen.",
        question_eight: "8. Wat zijn de visumvereisten voor Siargao?",
        answer_eight: "De meeste toeristen kunnen de Filipijnen zonder visum betreden voor 30 dagen. Indien nodig kun je je verblijf verlengen. Controleer de laatste visumregels en zorg ervoor dat je paspoort minstens zes maanden geldig is na je beoogde vertrekdatum.",
        question_nine: "9. Hoe kan ik me verplaatsen op Siargao?",
        answer_nine: "Je kunt Siargao rondreizen met behulp van tricycles, habal-habal (motorfiets taxi's), gehuurde scooters of fietsen, en busjes of privévoertuigen.",  
        question_ten: "10. Hoe is het weer op Siargao?",
        answer_ten: "Siargao heeft een tropisch klimaat met een regenseizoen van november tot februari en een droog seizoen van maart tot oktober. De beste tijd om te bezoeken is tijdens het droge seizoen voor zonnig weer.",
        language: "dutch"
    },
    {
        id: 7,
        question_one: "1. 如何前往希爾島？",
        answer_one: "要前往希爾島，請預訂從宿霧飛往Sayak機場的國內航班。如果你喜歡風景優美的路線，你也可以選擇從蘇里高市搭乘渡輪。抵達後，請安排當地交通前往你的住宿地點。",
        question_two: "2. 哪個時候是前往希爾島的最佳時間？",
        answer_two: "這取決於你尋找什麼！九月份是絕對最繁忙的月份。全國和國際衝浪比賽以及鎮上的慶典都在九月舉行。如果你正在尋找壯觀的浪潮，最好的時間是從九月到十一月。如果你想要人少的冷清浪潮，請在十二月到三月之間前來。這段時間不熱鬧是因為下雨。很多。如果你想學習衝浪，隨時都可以來。如果你不知道為什麼每個人都在談論衝浪，那麼四月到十月是白天沙灘、夜晚派對的完美時間。",
        question_three: "3. 希爾島必須參加的活動有哪些？",
        answer_three: "在希爾島，你必須在Cloud 9衝浪，遊覽Naked Island、Guyam Island和Daku Island，探索Sugba Lagoon，參觀獨特的Magpupungko Rock Pools，並享受General Luna充滿活力的夜生活。",
        question_four: "4. 在希爾島住在哪裡？",
        answer_four: "希爾島的熱門區域包括General Luna、Cloud 9，以及附近的村莊，如Pacifico和Dapa。這些地區提供各種各樣的住宿，從青年旅館到豪華度假村，以適應不同的預算和喜好。",
        question_five: "5. 前往希爾島的費用是多少？",
        answer_five: "在希爾島的預算旅行者可能每天花費約1,500到2,500菲律賓披索，而中档旅行者可能每天預算2,500到5,000菲律賓披索。對於奢華的旅行者來說，每天的開支可能超過5,000菲律賓披索。國內航班通常從7,500到16,000菲律賓披索來回，取決於你的出發地和預訂時間。",
        question_six: "6. 在希爾島使用的貨幣是什麼？",
        answer_six: "希爾島使用的貨幣是菲律賓披索（PHP）。",
        question_seven: "7. 前往希爾島安全嗎？",
        answer_seven: "對於旅行者來說，希爾島通常是安全的。但要注意一般的旅行預防措施，例如保管財物並注意天氣和海況。保持隨時了解當地的警告和健康建議。",
        question_eight: "8. 前往希爾島的簽證要求是什麼？",
        answer_eight: "大多數遊客可以免簽證進入菲律賓30天。如果需要，你可以延長你的停留時間。檢查最新的簽證規定，並確保你的護照在預定離境日期後至少六個月有效。",
        question_nine: "9. 如何在希爾島四處移動？",
        answer_nine: "你可以使用三輪車、摩托車出租（habal-habal）、租來的小型摩托車或自行車，以及面包車或私家車四處移動希爾島。",  
        question_ten: "10. 希爾島的天氣如何？",
        answer_ten: "希爾島的氣候是熱帶氣候，從11月到2月是雨季，3月到10月是旱季。最佳參觀時間是在旱季，享受陽光明媚的天氣。",
        language: "mandarin"
    },
    {
        id: 8,
        question_one: "1. Hur tar man sig till Siargao?",
        answer_one: "För att ta sig till Siargao, boka en inrikesflygning till Sayak Airport från Cebu. Om du föredrar en naturskön rutt kan du även ta en färja från Surigao City. När du kommer fram, ordna lokal transport till din boendeplats.",
        question_two: "2. När är det bästa att åka till Siargao?",
        answer_two: "Det beror på vad du letar efter! September är klart den mest hektiska månaden med nationella och internationella surfingtävlingar samt stadsfesten, allt i september. Om du letar efter episka vågor är september till november bäst. Om du vill undvika folkmassor, kom mellan december och mars. Det är glest med folk på grund av regn. Mycket regn. Om du vill lära dig surfa, kom när som helst. Om du inte har någon aning om varför alla pratar om surfing, är april till oktober perfekt för strandliv på dagen och fest på natten.",
        question_three: "3. Vilka är de måste-göra aktiviteterna i Siargao?",
        answer_three: "I Siargao måste du surfa vid Cloud 9, åka på ö-hopptur till Naked Island, Guyam Island och Daku Island, utforska Sugba Lagoon, besöka de unika Magpupungko Rock Pools och njuta av det pulserande nattlivet i General Luna.",
        question_four: "4. Var ska man bo i Siargao?",
        answer_four: "Populära områden att bo i Siargao inkluderar General Luna, Cloud 9 och närliggande byar som Pacifico och Dapa. Dessa områden erbjuder olika boendealternativ, från vandrarhem till lyxiga resorts, för att passa olika budgetar och preferenser.",
        question_five: "5. Hur mycket kostar det att resa till Siargao?",
        answer_five: "En budgetresenär i Siargao kan spendera runt 1 500 till 2 500 filippinska pesos per dag, medan en resenär med medelinkomst kan budgetera för 2 500 till 5 000 filippinska pesos per dag. För lyxresenärer kan dagliga kostnader överstiga 5 000 filippinska pesos. Inrikesflyg varierar vanligtvis mellan 7 500 och 16 000 filippinska pesos tur och retur, beroende på avreseplats och bokningstidpunkt.",
        question_six: "6. Vilken valuta används i Siargao?",
        answer_six: "Valutan som används i Siargao, Filippinerna, är filippinska pesos (PHP).",
        question_seven: "7. Är det säkert att resa till Siargao?",
        answer_seven: "Siargao är generellt sett säkert för resenärer. Men använd vanliga reseförsiktighetsåtgärder som att säkra dina tillhörigheter och vara medveten om väder- och havsförhållanden. Håll dig uppdaterad om lokala råd och hälsorekommendationer.",
        question_eight: "8. Vad är visumkraven för Siargao?",
        answer_eight: "De flesta turister kan komma in i Filippinerna utan visum i 30 dagar. Vid behov kan du förlänga din vistelse. Kontrollera de senaste viseringsreglerna och se till att ditt pass är giltigt minst sex månader efter din avsedda avresedatum.",
        question_nine: "9. Hur tar man sig runt i Siargao?",
        answer_nine: "Du kan ta dig runt i Siargao med hjälp av trehjulingar, habal-habal (motorcykeltaxi), hyrda mopeder eller cyklar och transporter som bussar eller privata fordon.",  
        question_ten: "10. Hur är vädret i Siargao?",
        answer_ten: "Siargao har ett tropiskt klimat med en regnperiod från november till februari och en torrperiod från mars till oktober. Bästa tiden att besöka är under den torra perioden för soligt väder.",
        language: "swedish"
    },
    {
        id: 9,
        question_one: "1. Как добраться до Сиаргао?",
        answer_one: "Чтобы добраться до Сиаргао, забронируйте внутренний рейс до аэропорта Саяк из Себу. Если вы предпочитаете живописный маршрут, вы также можете взять паром из города Суригао. После прибытия организуйте местный транспорт до вашего размещения.",
        question_two: "2. Когда лучше поехать в Сиаргао?",
        answer_two: "Это зависит от того, что вы ищете! Сентябрь является самым загруженным месяцем. В этом месяце проходят национальные и международные соревнования по серфингу, а также городской праздник. Если вы ищете эпические волны, лучшее время с сентября по ноябрь. Если вы хотите избежать толп, приезжайте с декабря по март. Это тихий период, потому что идет дождь. Много дождя. Если вы хотите научиться серфить, приезжайте в любое время. Если у вас нет понятия, почему все говорят о серфинге, то апрель - октябрь идеальны для пляжного отдыха днем и вечеринок ночью.",
        question_three: "3. Какие обязательные мероприятия на Сиаргао?",
        answer_three: "На Сиаргао вы должны покататься на доске на Клауд 9, отправиться в островное турне на острова Naked, Guyam и Daku, исследовать лагуну Sugba, посетить уникальные бассейны из скал Magpupungko и насладиться активной ночной жизнью в Дженерал Луна.",
        question_four: "4. Где остановиться на Сиаргао?",
        answer_four: "Популярные районы для проживания на Сиаргао включают Генерал Луна, Клауд 9 и близлежащие деревни, такие как Пасифико и Дапа. В этих районах представлены различные варианты размещения, от хостелов до роскошных курортов, подходящих для разных бюджетов и предпочтений.",
        question_five: "5. Сколько стоит поездка на Сиаргао?",
        answer_five: "Бюджетный путешественник на Сиаргао может тратить около 1 500-2 500 филиппинских песо в день, тогда как путешественник среднего класса может рассчитывать на 2 500-5 000 филиппинских песо в день. Для люксовых путешественников ежедневные расходы могут превышать 5 000 филиппинских песо. Внутренние рейсы обычно стоят от 7 500 до 16 000 филиппинских песо туда и обратно, в зависимости от вашего места отправления и времени бронирования.",
        question_six: "6. Какая валюта используется на Сиаргао?",
        answer_six: "Валюта, используемая на Сиаргао, Филиппины - это филиппинское песо (PHP).",
        question_seven: "7. Безопасно ли путешествовать на Сиаргао?",
        answer_seven: "Сиаргао в целом безопасна для путешественников. Тем не менее, соблюдайте общие меры предосторожности при путешествии, такие как обеспечение безопасности вещей и внимание к погодным и морским условиям. Следите за местными предупреждениями и рекомендациями по здоровью.",
        question_eight: "8. Какие требования к визе для Сиаргао?        ",
        answer_eight: "Большинство туристов могут въезжать на Филиппины без визы на 30 дней. При необходимости можно продлить ваше пребывание. Проверьте последние правила визита и убедитесь, что ваш паспорт действителен как минимум шесть месяцев после предполагаемой даты выезда.        ",
        question_nine: "9. Как передвигаться на Сиаргао?",
        answer_nine: "Передвигаться по Сиаргао можно на трициклах, мототакси habal-habal, арендованных скутерах или велосипедах, а также на фургонах или частных автомобилях. ",  
        question_ten: "10. Какая погода на Сиаргао?",
        answer_ten: "На Сиаргао тропический климат с дождливым сезоном с ноября по февраль и сухим сезоном с марта по октябрь. Лучшее время для посещения - сухой сезон для солнечной погоды.",
        language: "russian"
    },   
    {
        id: 10,
        question_one: "1. 시아르가오에 가는 방법은?",
        answer_one: "시아르가오에 가려면 세부에서 세악 공항으로 국내 항공편을 예약하세요. 풍경이 아름다운 루트를 선호한다면 수리가오 시티에서 페리를 탈 수도 있습니다. 도착하면 숙소까지의 현지 교통 수단을 조정하세요.",
        question_two: "2. 시아르가오 여행의 최적 시기는 언제인가요?",
        answer_two: "이것은 당신이 찾는 것에 달려 있습니다! 9월은 절대적으로 가장 붐비는 달입니다. 9월에는 국내 및 국제 서핑 대회와 도시 축제가 열립니다. 장엄한 파도를 찾는다면 9월부터 11월까지가 가장 적절합니다. 사람이 적은 서핑을 찾는다면 12월부터 3월까지 방문하세요. 이 기간은 비가 많이 오기 때문에 조용합니다. 서핑을 배우려면 언제든지 와도 좋습니다. 모두가 서핑에 대해 계속 이야기하는 이유를 모르겠다면 4월부터 10월까지가 하루 종일 해변에서 즐기고 밤에는 파티하기에 완벽합니다.",
        question_three: "3. 시아르가오에서 반드시 해야 할 활동은 무엇인가요?",
        answer_three: "시아르가오에서는 Cloud 9에서 서핑을 즐기고 Naked Island, Guyam Island, Daku Island으로 섬 여행을 떠나고 Sugba Lagoon을 탐험하며 독특한 Magpupungko Rock Pools을 방문하고 General Luna에서 활기찬 나이트라이프를 즐기는 것이 반드시해야 할 활동입니다.",
        question_four: "4. 시아르가오에서 어디에 머무를까요?",
        answer_four: "시아르가오에서 인기 있는 지역은 General Luna, Cloud 9 및 Pacifico 및 Dapa와 같은 인근 마을입니다. 이러한 지역에서는 다양한 예산과 선호도에 맞는 여러 숙소가 제공됩니다.",
        question_five: "5. 시아르가오 여행 비용은 얼마나 드나요?",
        answer_five: "시아르가오에서의 저렴한 여행자는 일일 약 1,500에서 2,500 필리핀 페소를 소비할 것이며 중급 여행자는 하루 약 2,500에서 5,000 필리핀 페소를 예산으로 잡을 것입니다. 고급 여행자의 경우 일일 비용은 5,000 필리핀 페소를 초과할 수 있습니다. 국내 항공편은 일반적으로 7,500에서 16,000 필리핀 페소 사이의 왕복이며 출발지와 예약 시기에 따라 다릅니다.",
        question_six: "6. 시아르가오에서 사용되는 통화는 무엇인가요?",
        answer_six: "시아르가오에서 사용되는 통화는 필리핀 페소 (PHP)입니다.",
        question_seven: "7. 시아르가오 여행은 안전한가요?",
        answer_seven: "시아르가오는 일반적으로 여행자들에게 안전합니다. 그러나 물품을 안전하게 보관하고 날씨와 해상 조건에 주의하는 등 일반적인 여행 주의사항을 적용하세요. 지역 통보 및 보건 권고사항을 업데이트하십시오.",
        question_eight: "8. 시아르가오의 비자 요건은 무엇인가요?",
        answer_eight: "대부분의 관광객은 30일 동안 비자 없이 필리핀에 입국할 수 있습니다. 필요한 경우 체류 기간을 연장할 수 있습니다. 최신 비자 규정을 확인하고 출국 예정일로부터 최소 여섯 개월 이상 유효한 여권이 있는지 확인하세요.",
        question_nine: "9. 시아르가오에서 이동하는 방법은 무엇인가요?",
        answer_nine: "시아르가오에서는 삼륜차, 하발-하발 (오토바이 택시), 렌트 스쿠터 또는 자전거, 그리고 밴이나 개인 차량을 이용하여 이동할 수 있습니다.",  
        question_ten: "10. 시아르가오의 날씨는 어떻게 되나요?",
        answer_ten: "시아르가오는 11월부터 2월까지의 비젖풍기와 3월부터 10월까지의 건조한 계절을 가진 열대 기후를 가지고 있습니다. 가장 좋은 방문 시기는 맑은 날씨를 즐길 수 있는 건조한 계절입니다.",
        language: "hangul"
    },
    {
        id: 11,
        question_one: "1. Come arrivare a Siargao?",
        answer_one: "Per raggiungere Siargao, prenota un volo domestico per l'aeroporto di Sayak da Cebu. Se preferisci un percorso panoramico, puoi prendere opzionalmente un traghetto da Surigao City. Una volta arrivato, organizza il trasporto locale verso la tua sistemazione.",
        question_two: "2. Quando è il miglior momento per andare a Siargao?        ",
        answer_two: "Dipende da cosa stai cercando! Settembre è di gran lunga il mese più affollato. Le competizioni nazionali e internazionali di surf e la festa del paese sono tutte a settembre. Se cerchi onde epiche, sono migliori da settembre a novembre. Se cerchi onde tranquille, vieni da dicembre a marzo. È tranquillo perché piove. Molto. Se vuoi imparare a surfare, vieni in qualsiasi momento. Se non capisci perché tutti parlano di surf, allora aprile-ottobre è perfetto per la spiaggia tutto il giorno e festa tutta la notte.",
        question_three: "3. Quali sono le attività imperdibili a Siargao?",
        answer_three: "A Siargao, devi fare surf a Cloud 9, fare un'escursione alle isole Naked, Guyam e Daku, esplorare la laguna di Sugba, visitare le particolari Magpupungko Rock Pools e goderti la vivace vita notturna a General Luna. ",
        question_four: "4. Dove alloggiare a Siargao? ",
        answer_four: "Le aree popolari per alloggiare a Siargao includono General Luna, Cloud 9 e i villaggi circostanti come Pacifico e Dapa. Queste aree offrono una gamma di sistemazioni, da ostelli a resort di lusso, per soddisfare diversi budget e preferenze. ",
        question_five: "5. Quanto costa viaggiare a Siargao?",
        answer_five: "Un viaggiatore con un budget a Siargao potrebbe spendere circa 1.500-2.500 pesos filippini al giorno, mentre un viaggiatore di media gamma potrebbe pianificare un budget di 2.500-5.000 pesos filippini al giorno. Per i viaggiatori di lusso, le spese giornaliere potrebbero superare i 5.000 pesos filippini. I voli domestici variano generalmente da 7.500 a 16.000 pesos filippini a/r, a seconda della tua località di partenza e del momento della prenotazione.",
        question_six: "6. Qual è la valuta a Siargao?",
        answer_six: "La valuta utilizzata a Siargao, Filippine, è il Peso Filippino (PHP).",
        question_seven: "7. È sicuro viaggiare a Siargao?",
        answer_seven: "Siargao è generalmente sicura per i viaggiatori. Tuttavia, segui precauzioni comuni durante i viaggi, come assicurare i bagagli e prestare attenzione alle condizioni meteorologiche e del mare. Mantieniti aggiornato su eventuali avvisi locali e raccomandazioni sanitarie.",
        question_eight: "8. Quali sono i requisiti del visto per Siargao?",
        answer_eight: "La maggior parte dei turisti può entrare nelle Filippine senza visto per 30 giorni. Se necessario, è possibile estendere il soggiorno. Controlla le ultime regole sui visti e assicurati che il passaporto sia valido per almeno sei mesi oltre la data prevista di partenza.",
        question_nine: "9. Come muoversi a Siargao?",
        answer_nine: "Puoi spostarti a Siargao utilizzando tricicli, habal-habal (moto taxi), scooter o biciclette noleggiate, e furgoni o veicoli privati.",  
        question_ten: "10. Com'è il clima a Siargao?",
        answer_ten: "Siargao ha un clima tropicale con una stagione delle piogge da novembre a febbraio e una stagione secca da marzo a ottobre. Il periodo migliore per visitare è durante la stagione secca per un clima soleggiato.",
        language: "italian"
    },
    {
        id: 12,
        question_one: "1. シャルガオへの行き方は？",
        answer_one: "シャルガオに行くには、セブからセヤック空港への国内線のフライトを予約してください。風光明媚な経路を好む場合、スリガオ市からのフェリーも選択肢となります。到着後は、宿泊先までの地元の交通手段を手配してください。",
        question_two: "2. シャルガオへのベストな時期はいつですか？",
        answer_two: "それはあなたが求めているものに依存します！ 9月ははるかに最も忙しい月です。国内外のサーフィン大会や町の祭りがすべて9月に行われます。壮大な波を求めるなら9月から11月が最適です。混雑を避けたいなら12月から3月に訪れてください。雨が多いため静かです。たくさんの雨が降ります。サーフィンを学びたいならいつでも来てください。なぜみんながサーフィンの話をしているのか分からない場合、4月から10月は昼はビーチで遊び、夜はパーティーに最適です。",
        question_three: "3. シャルガオでの必須アクティビティは何ですか？",
        answer_three: "シャルガオでは、Cloud 9でサーフィンをし、Naked Island、Guyam Island、Daku Islandへのアイランドホッピングを楽しんで、Sugba Lagoonを探索し、独特のMagpupungko Rock Poolsを訪れ、General Lunaの活気あるナイトライフを楽しむ必要があります。",
        question_four: "4. シャルガオでの滞在先はどこですか？",
        answer_four: "シャルガオでの人気のあるエリアには、General Luna、Cloud 9、およびPacificoやDapaの近隣の村があります。これらのエリアでは、異なる予算と好みに合わせてホステルから高級リゾートまでさまざまな宿泊施設が提供されています。",
        question_five: "5. シャルガオへの旅費はいくらかかりますか？",
        answer_five: "シャルガオでの予算旅行者は、1日あたり約1,500から2,500フィリピンペソを使うかもしれません。一般的な旅行者は1日あたり2,500から5,000フィリピンペソを予算にするかもしれません。贅沢な旅行者の場合、1日の経費は5,000フィリピンペソを超えるかもしれません。国内線のフライトは通常、発着地と予約のタイミングによって7,500から16,000フィリピンペソの範囲で変動します。",
        question_six: "6. シャルガオで使用されている通貨は何ですか？",
        answer_six: "シャルガオで使用されている通貨はフィリピンペソ（PHP）です。",
        question_seven: "7. シャルガオへの旅行は安全ですか？",
        answer_seven: "シャルガオは一般的に旅行者にとって安全です。ただし、財産を保護し、天候や海の状況に注意するなど、一般的な旅行の注意が必要です。地元の勧告と健康の推奨事項を常に更新してください。",
        question_eight: "8. シャルガオのビザ要件は何ですか？",
        answer_eight: "ほとんどの観光客は30日のビザなしでフィリピンに入国できます。必要な場合は滞在を延長できます。最新のビザ規則を確認し、予定の出発日から少なくとも6か月間は有効なパスポートを持っていることを確認してください。",
        question_nine: "9. シャルガオでの移動手段は何ですか？",
        answer_nine: "シャルガオではトライシクル、ハバル-ハバル（オートバイタクシー）、レンタルスクーターや自転車、バンやプライベート 車を利用して移動できます。",  
        question_ten: "10. シャルガオの天気はどうですか？",
        answer_ten: "シャルガオは11月から2月までの雨季と3月から10月までの乾季を持つ熱帯気候です。晴れた天気を楽しむためのベストな時期は乾季です。",
        language: "japanese"
    },
    {
        id: 13,
        question_one: "1. Como chegar a Siargao?",
        answer_one: "Para chegar a Siargao, reserve um voo doméstico para o Aeroporto de Sayak, partindo de Cebu. Se preferir uma rota cênica, pode opcionalmente pegar uma balsa saindo de Surigao City. Ao chegar, faça os arranjos para o transporte local até a sua acomodação.",
        question_two: "2. Qual é a melhor época para ir a Siargao?",
        answer_two: "Depende do que você está procurando! Setembro é, de longe, o mês mais movimentado. Os campeonatos nacionais e internacionais de surfe e a festa da cidade acontecem todos em setembro. Se você está em busca de ondas épicas, o melhor período é de setembro a novembro. Se procura surfe com menos pessoas, venha de dezembro a março, que é um período menos movimentado devido à chuva. Se quiser aprender a surfar, venha a qualquer momento. Se você não entende por que todos falam tanto sobre surfe, então abril a outubro são ideais para passar o dia na praia e festejar durante a noite.",
        question_three: "3. Quais são as atividades imperdíveis em Siargao?",
        answer_three: "Em Siargao, você deve surfar em Cloud 9, fazer um passeio pelas ilhas Naked, Guyam e Daku, explorar a Lagoa de Sugba, visitar as únicas Piscinas de Rocha Magpupungko e aproveitar a animada vida noturna em General Luna.",
        question_four: "4. Onde ficar em Siargao?",
        answer_four: "Áreas populares para se hospedar em Siargao incluem General Luna, Cloud 9 e vilarejos próximos como Pacifico e Dapa. Essas áreas oferecem uma variedade de acomodações, desde hostels até resorts de luxo, para atender a diferentes orçamentos e preferências.",
        question_five: "5. Quanto custa viajar para Siargao?",
        answer_five: "Um viajante econômico em Siargao pode gastar cerca de 1.500 a 2.500 pesos filipinos por dia, enquanto um viajante de médio porte pode orçar de 2.500 a 5.000 pesos filipinos por dia. Para viajantes de luxo, os gastos diários podem ultrapassar 5.000 pesos filipinos. Os voos domésticos geralmente variam de 7.500 a 16.000 pesos filipinos, ida e volta, dependendo do local de partida e do momento da reserva.",
        question_six: "6. Qual é a moeda em Siargao?",
        answer_six: "A moeda usada em Siargao, Filipinas, é o Peso Filipino (PHP).",
        question_seven: "7. É seguro viajar para Siargao?",
        answer_seven: "Siargao é geralmente seguro para os viajantes. No entanto, tome precauções comuns durante as viagens, como garantir pertences e estar ciente das condições meteorológicas e do mar. Mantenha-se atualizado sobre quaisquer avisos locais e recomendações de saúde.",
        question_eight: "8. Quais são os requisitos de visto para Siargao?",
        answer_eight: "A maioria dos turistas pode entrar nas Filipinas sem visto por 30 dias. Se necessário, é possível estender a estadia. Verifique as últimas regras de visto e certifique-se de que seu passaporte tenha validade de pelo menos seis meses após a data pretendida de partida.",
        question_nine: "9. Como se locomover em Siargao?",
        answer_nine: "Você pode se locomover em Siargao usando triciclos, habal-habal (táxis de motocicleta), scooters ou bicicletas alugadas, e vans ou veículos privados.",  
        question_ten: "10. Como é o clima em Siargao?",
        answer_ten: "Siargao tem um clima tropical, com uma estação chuvosa de novembro a fevereiro e uma estação seca de março a outubro. A melhor época para visitar é durante a estação seca, para um clima ensolarado.",
        language: "portuguese"
    },
    {
        id: 14,
        question_one: "1. Hvordan kommer man til Siargao?",
        answer_one: "For at komme til Siargao, skal du booke en indenrigsflyvning til Sayak Lufthavn fra Cebu. Hvis du foretrækker en malerisk rute, kan du valgfrit tage en færge fra Surigao City. Når du ankommer, skal du arrangere lokal transport til din indkvartering.",
        question_two: "2. Hvornår er det bedste tidspunkt at besøge Siargao?",
        answer_two: "Det afhænger af, hvad du leder efter! September er klart den travleste måned. De nationale og internationale surfkonkurrencer samt byens festival finder sted i september. Hvis du leder efter episke bølger, er de bedst fra september til november. Hvis du leder efter ufyldt surf, kom fra december til marts. Det er ufyldt, fordi det regner. Meget. Hvis du vil lære at surfe, så kom når som helst. Hvis du ikke har nogen idé om, hvorfor alle bliver ved med at tale om surfing, så er april til oktober perfekt til stranden hele dagen og fest hele natten.",
        question_three: "3. Hvad er must-do aktiviteterne i Siargao?",
        answer_three: "I Siargao skal du surfe på Cloud 9, tage på ø-hop til Naked Island, Guyam Island og Daku Island, udforske Sugba Lagoon, besøge de unikke Magpupungko Rock Pools og nyde det livlige natteliv i General Luna.",
        question_four: "4. Hvor skal man bo i Siargao?",
        answer_four: "Populære områder at bo i Siargao inkluderer General Luna, Cloud 9 og nærliggende landsbyer som Pacifico og Dapa. Disse områder tilbyder et udvalg af overnatningsmuligheder, lige fra vandrerhjem til luksusresorts, der passer til forskellige budgetter og præferencer.",
        question_five: "5. Hvor meget koster det at rejse til Siargao?",
        answer_five: "En budgetrejsende i Siargao kan bruge omkring 1.500 til 2.500 filippinske pesos om dagen, mens en mellemklasse-rejsende kunne budgettere med 2.500 til 5.000 filippinske pesos om dagen. For luksusrejsende kunne de daglige udgifter overstige 5.000 filippinske pesos. Indenrigsflyvninger ligger typisk mellem 7.500 og 16.000 filippinske pesos for en rundtur, afhængigt af din afrejselokation og bookingtidspunkt.",
        question_six: "6. Hvad er valutaen i Siargao?",
        answer_six: "Valutaen, der bruges i Siargao, Filippinerne, er den filippinske peso (PHP).",
        question_seven: "7. Er det sikkert at rejse til Siargao?",
        answer_seven: "Siargao er generelt sikkert for rejsende. Men udvis almindelige rejseforholdsregler, såsom at sikre ejendele og være opmærksom på vejr- og havforholdene. Hold dig opdateret om eventuelle lokale anbefalinger og sundhedsanbefalinger.",
        question_eight: "8. Hvad er visumkravene for Siargao?",
        answer_eight: "De fleste turister kan komme ind i Filippinerne uden visum i 30 dage. Hvis nødvendigt kan du forlænge dit ophold. Tjek de seneste visumregler og sørg for, at dit pas er gyldigt i mindst seks måneder ud over din planlagte afrejsedato.",
        question_nine: "9. Hvordan kan jeg komme rundt i Siargao?",
        answer_nine: "Du kan komme rundt i Siargao ved at bruge tricykler, habal-habal (motorcykeltaxier), lejede scootere eller cykler samt varevogne eller private køretøjer.",  
        question_ten: "10. Hvordan er vejret i Siargao?",
        answer_ten: "Siargao har et tropisk klima med en regntid fra november til februar og en tørketid fra marts til oktober. Det bedste tidspunkt at besøge er i tørketiden for solrigt vejr.",
        language: "danish"
    },
   
  
];

module.exports = genList;