const touristList = [
    {
        id: 1,
        name: "Cloud 9 Surfing Area",
        location: "R578+F36 Siargao Island, General Luna, Surigao del Norte",
        open_hours: "Open 24 hours",
        image: "https://i.imgur.com/xGAoszZ.png",
        likes: "",
    },
    {
        id: 2,
        name: "Sohoton Cove",
        location: "Socorro, Surigao del Norte, Philippines",
        open_hours: "7:00 AM - 4:00 PM",
        image: "https://i.imgur.com/E2qawlD.png",
        likes: "",
    },
    {
        id: 3,
        name: "Magpupungko Rock Pools",
        location: "Pilar",
        open_hours: "Open 24 hours",
        image: "https://i.imgur.com/1PuHbqX.png",
        likes: "",
    },
    {
        id: 4,
        name: "Sugba Lagoon",
        location: "Del Carmen, Surigao del Norte",
        open_hours: "7 AM–5 PM",
        image: "https://i.imgur.com/4hUHFvD.png",
        likes: "",
    },
    {
        id: 5,
        name: "Guyam Island",
        location: "General Luna",
        open_hours: "Open 24 hours",
        image: "https://i.imgur.com/XzjjeKd.png",
        likes: "",
    },
    {
        id: 6,
        name: "Daku Island",
        location: "General Luna",
        open_hours: "Open 24 hours",
        image: "https://i.imgur.com/04kBqfT.png",
        likes: "",
    },
    {
        id: 7,
        name: "Taktak Falls",
        location: "22MV+MCF, Santa Monica, Surigao del Norte",
        open_hours: "8:00 AM - 5:00 PM",
        image: "https://i.imgur.com/IHsAjGY.png",
        likes: "",
    },
    {
        id: 8,
        name: "Maasin Bridge  River Swing",
        location: "R3C4+HFW, Siargao Circumferential Rd, Dapa, Surigao del Norte",
        open_hours: "7:30 AM–6:00 PM",
        image: "https://i.imgur.com/dZV3dg1.png",
        likes: "",
    },
    {
        id: 9,
        name: "Naked Island",
        location: "P4MG+WCR, Siargao Island, Union Rd, Dapa, Surigao del Norte",
        open_hours: "Open 24 hours",
        image: "https://i.imgur.com/r3BbD6M.png",
        likes: "",
    },
    {
        id: 10,
        name: "Coconut Tree Viewpoin",
        location: "R366+V37, Siargao Circumferential Rd, Dapa, Surigao del Norte",
        open_hours: "7:30 AM–8:50 PM",
        image: "https://i.imgur.com/eZKQ5eb.png",
        likes: "",
    }
];

module.exports = touristList;